const fallback={Julai:[{name:"1 Cendekia",score:47,records:1},{name:"2 Gigih",score:45,records:1},{name:"2 Ikhlas",score:45,records:1},{name:"2 Bestari",score:41.67,records:3},{name:"1 Murni",score:41,records:1}],Februari:[{name:"2 Bestari",score:41,records:1},{name:"2 Adil",score:40,records:1},{name:"2 Kreatif",score:34.5,records:2},{name:"2 Dedikasi",score:32,records:2},{name:"2 Rasional",score:30,records:2}],Mac:[{name:"1 Cendekia",score:43,records:2},{name:"2 Bestari",score:40.5,records:2},{name:"1 Dedikasi",score:38,records:1},{name:"2 Rasional",score:36.5,records:2},{name:"1 Kreatif",score:34,records:1}]};
let monthlyData={...fallback},classes=[];const $=s=>document.querySelector(s),month=$('#month'),modal=$('#moduleModal'),content=$('#modalContent');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function place(x,n,c){return `<article class="place ${c}">${n===1?'<span class="crown">♛</span>':''}<span class="medal">${n===1?'🥇':n===2?'🥈':'🥉'}</span><div class="avatar">${esc(x.name.split(' ')[0])}</div><h3>${esc(x.name)}</h3><strong>${Number(x.score).toFixed(2)}</strong><div class="plinth">${n}</div></article>`}
function current(){return monthlyData[month.value]||fallback.Julai}
function render(){const m=month.value,d=current();$('#champion').textContent=d[0]?.name||'-';$('#topScore').textContent=Number(d[0]?.score||0).toFixed(2);$('#podiumMonth').textContent=m;$('#aiMonth').textContent=m;if(d.length>=3)$('#podium').innerHTML=place(d[1],2,'second')+place(d[0],1,'first')+place(d[2],3,'third');$('#recordCount').textContent=d.reduce((a,b)=>a+Number(b.records||0),0)+' rekod terpilih';$('#summary').innerHTML=d[0]?`Tahniah kepada <b>${esc(d[0].name)}</b> sebagai peneraju dengan purata <b>${Number(d[0].score).toFixed(2)}</b>. Prestasi kelas akan dikemas kini mengikut rekod Google Sheets.`:'Belum ada data.';$('#rankingList').innerHTML=d.map((x,i)=>`<div class="rank-row"><span>${i+1}</span><b>${esc(x.name)}</b><div><i style="width:${Math.min(100,Number(x.score)*2)}%"></i></div><strong>${Number(x.score).toFixed(2)}</strong></div>`).join('')}
async function api(params={}){if(!CONFIG.API_URL)throw new Error('URL Apps Script belum dipasang');const u=new URL(CONFIG.API_URL);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw new Error('Sambungan gagal');const j=await r.json();if(j.success===false)throw new Error(j.message||'Ralat sistem');return j}
async function loadData(){try{const j=await api({action:'dashboard'});if(j.monthlyData)monthlyData=j.monthlyData;if(j.classes)classes=j.classes;const months=Object.keys(monthlyData);month.innerHTML=months.map(x=>`<option>${esc(x)}</option>`).join('');month.value=months.includes('Julai')?'Julai':months[0];render();toast('Data Google Sheets berjaya dimuatkan')}catch(e){render();toast(CONFIG.API_URL?e.message:'Paparan demo — pasang URL dalam config.js') }}
function openModal(title,html){$('#activeLabel').textContent=title;content.innerHTML=`<p class="eyebrow">MODUL 3K SMART AI</p><h2>${esc(title)}</h2>${html}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function rankingHTML(){return `<div class="table-wrap"><table><thead><tr><th>Rank</th><th>Kelas</th><th>Purata</th><th>Rekod</th></tr></thead><tbody>${current().map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td><td>${Number(x.score).toFixed(2)}</td><td>${x.records}</td></tr>`).join('')}</tbody></table></div>`}
function formHTML(){const opts=classes.length?classes:['1 ADIL','1 BESTARI','1 CENDEKIA','2 ADIL','2 BESTARI','2 CENDEKIA'];return `<form id="scoreForm" class="score-form"><label>Tarikh<input type="date" name="tarikh" required></label><label>Kelas<select name="kelas" required><option value="">Pilih kelas</option>${opts.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><div class="criteria">${['Lantai','Cermin Tingkap','Peralatan','Jadual Bertugas','Sudut NILAM','Susunan Meja','Carta Organisasi','Info Semasa','Hiasan'].map((x,i)=>`<label>${i+1}. ${x}<input type="number" name="k${i+1}" min="0" max="10" value="0" required></label>`).join('')}</div><label>Catatan<textarea name="catatan" rows="3" placeholder="Catatan juri"></textarea></label><button type="submit" class="primary">Simpan Penilaian</button><p class="form-note">Simpanan memerlukan URL Apps Script dalam config.js.</p></form>`}
function galleryHTML(){return `<div class="empty-state"><span>🖼️</span><h3>Galeri Bukti 3K</h3><p>Gambar daripada lajur Gambar_Bukti akan dipaparkan selepas sambungan Google Sheets diaktifkan.</p></div>`}
function analysisHTML(){const d=current(),top=d[0],low=d[d.length-1];return `<div class="insight-grid"><article><small>Juara Semasa</small><strong>${esc(top?.name||'-')}</strong><p>Purata ${Number(top?.score||0).toFixed(2)}</p></article><article><small>Perlu Bimbingan</small><strong>${esc(low?.name||'-')}</strong><p>Purata ${Number(low?.score||0).toFixed(2)}</p></article></div><div class="ai-note">🤖 Cadangan AI: Berikan penghargaan kepada kelas teratas dan fokuskan pemantauan mingguan kepada kelas yang menunjukkan purata lebih rendah.</div>`}
function openModule(name){const map={'Isi Penilaian':formHTML(),'Ranking 3K':rankingHTML(),'Analisis Pintar':analysisHTML(),'Hall of Fame':`<div class="fame">${current().slice(0,3).map((x,i)=>`<article><span>${['🥇','🥈','🥉'][i]}</span><h3>${esc(x.name)}</h3><b>${Number(x.score).toFixed(2)}</b></article>`).join('')}</div>`,'Prestasi Kelas':rankingHTML(),'Galeri Bukti':galleryHTML(),'Laporan & PDF':`<div class="empty-state"><span>📄</span><h3>Laporan Bulanan</h3><p>Klik untuk cetak paparan semasa atau simpan sebagai PDF.</p><button class="primary" onclick="window.print()">Cetak / Simpan PDF</button></div>`,'Pengumuman':`<div class="notice"><b>📢 Liga Adiwira Ceria 2026</b><p>Penilaian kelas dijalankan mengikut jadual Unit 3K. Pastikan kelas bersih, ceria dan selamat.</p></div>`,'Panel Pentadbir':`<div class="empty-state"><span>🔐</span><h3>Panel Pentadbir</h3><p>Kemas kini data terus melalui Google Sheets Unit 3K.</p><a class="primary link-button" href="https://docs.google.com/spreadsheets/d/1Yz78l8Q95_JfvrDtra_NXrEzR8UHyftn7RXo7OaO1sU/edit" target="_blank">Buka Google Sheets</a></div>`};openModal(name,map[name]||'<p>Modul sedang disediakan.</p>');if(name==='Isi Penilaian')$('#scoreForm').addEventListener('submit',saveScore)}
async function saveScore(e){e.preventDefault();const f=new FormData(e.currentTarget),payload=Object.fromEntries(f.entries());try{const j=await api({action:'save',data:JSON.stringify(payload)});toast(j.message||'Penilaian berjaya disimpan');modal.classList.remove('open');await loadData()}catch(err){toast(err.message)}}
month.addEventListener('change',render);$('#refresh').addEventListener('click',async e=>{const b=e.currentTarget;b.textContent='Memuat data…';await loadData();b.textContent='✓ Data Dikemas Kini';setTimeout(()=>b.textContent='↻ Segarkan Data',1500)});document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>openModule(b.dataset.menu)));$('#modalClose').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});render();loadData();
